name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install & Test Backend
        working-directory: backend
        run: |
          npm install
          npm run test

      - name: Install & Test Frontend
        working-directory: frontend
        run: |
          npm install
          npm run lint

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build & Push Frontend Image
        run: |
          docker build -t nikhil788/taskmanager-frontend ./frontend
          docker push nikhil788/taskmanager-frontend

      - name: Build & Push Backend Image
        run: |
          docker build -t nikhil788/taskmanager-backend ./backend
          docker push nikhil788/taskmanager-backend

  deploy-to-staging:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Staging
        run: |
          echo "Deploying to staging..."
          # Example: ssh your-user@staging-server 'cd /app && docker-compose pull && docker-compose up -d'

  deploy-to-production:
    needs: deploy-to-staging
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Deploy to Production
        run: |
          echo "Deploying to production..."
          # Example: ssh your-user@prod-server 'cd /app && docker-compose pull && docker-compose up -d'
